functions/app/routes.py
from flask import Blueprint, render_template, session, redirect, url_for, current_app, jsonify, flash

main_bp = Blueprint('main_bp', __name__)

@main_bp.route('/')
def welcome():
    return render_template('flowbite.html')

@main_bp.route('/base')
def base():
    return render_template('base.html')

@main_bp.route('/dashboard')
def dashboard():
    books = [
        {"ten_sach": "To Kill a Mockingbird", "chu_de": "Novel", "ngon_ngu": "English", "so_trang": 281, "so_tu": "1099"},
        {"ten_sach": "1984", "chu_de": "Dystopian", "ngon_ngu": "English", "so_trang": 328, "so_tu": "1599"},
        {"ten_sach": "The Great Gatsby", "chu_de": "Novel", "ngon_ngu": "English", "so_trang": 180, "so_tu": "1099"},
        {"ten_sach": "Moby Dick", "chu_de": "Adventure", "ngon_ngu": "English", "so_trang": 635, "so_tu": "1299"},
        {"ten_sach": "War and Peace", "chu_de": "Historical", "ngon_ngu": "Russian", "so_trang": 1225, "so_tu": "2099"},
        {"ten_sach": "Pride and Prejudice", "chu_de": "Romance", "ngon_ngu": "English", "so_trang": 279, "so_tu": "939"},
        {"ten_sach": "The Catcher in the Rye", "chu_de": "Novel", "ngon_ngu": "English", "so_trang": 277, "so_tu": "869"},
        {"ten_sach": "The Hobbit", "chu_de": "Fantasy", "ngon_ngu": "English", "so_trang": 310, "so_tu": "1499"},
        {"ten_sach": "Crime and Punishment", "chu_de": "Philosophical", "ngon_ngu": "Russian", "so_trang": 430, "so_tu": "1199"},
        {"ten_sach": "The Brothers Karamazov", "chu_de": "Philosophical", "ngon_ngu": "Russian", "so_trang": 796, "so_tu": "1899"}
    ]
    data = [
        {"ten_sach": "To Kill a Mockingbird", "ngay_thao_tac": "22 May 2024", "thao_tac": "Dịch", "tinh_trang": "Đang xử lý", "xem_chi_tiet": "Xem chi tiết"},
        {"ten_sach": "1984", "ngay_thao_tac": "20 May 2024", "thao_tac": "Sách nói", "tinh_trang": "Đã hoàn thành", "xem_chi_tiet": "Xem chi tiết"},
        {"ten_sach": "The Great Gatsby", "ngay_thao_tac": "18 May 2024", "thao_tac": "Lưu trữ", "tinh_trang": "Đã huỷ", "xem_chi_tiet": "Xem chi tiết"},
        {"ten_sach": "Moby Dick", "ngay_thao_tac": "15 May 2024", "thao_tac": "Lưu sách", "tinh_trang": "Không thành công", "xem_chi_tiet": "Xem chi tiết"},
        {"ten_sach": "War and Peace", "ngay_thao_tac": "10 May 2024", "thao_tac": "Cộng đồng", "tinh_trang": "Đang xử lý", "xem_chi_tiet": "Xem chi tiết"},
        {"ten_sach": "Pride and Prejudice", "ngay_thao_tac": "08 May 2024", "thao_tac": "Dịch", "tinh_trang": "Đã hoàn thành", "xem_chi_tiet": "Xem chi tiết"},
        {"ten_sach": "The Catcher in the Rye", "ngay_thao_tac": "05 May 2024", "thao_tac": "Sách nói", "tinh_trang": "Đã huỷ", "xem_chi_tiet": "Xem chi tiết"},
        {"ten_sach": "The Hobbit", "ngay_thao_tac": "03 May 2024", "thao_tac": "Lưu trữ", "tinh_trang": "Đang xử lý", "xem_chi_tiet": "Xem chi tiết"},
        {"ten_sach": "Crime and Punishment", "ngay_thao_tac": "01 May 2024", "thao_tac": "Lưu sách", "tinh_trang": "Không thành công", "xem_chi_tiet": "Xem chi tiết"},
        {"ten_sach": "The Brothers Karamazov", "ngay_thao_tac": "28 April 2024", "thao_tac": "Cộng đồng", "tinh_trang": "Đang xử lý", "xem_chi_tiet": "Xem chi tiết"},
        {"ten_sach": "Brave New World", "ngay_thao_tac": "25 April 2024", "thao_tac": "Dịch", "tinh_trang": "Đã hoàn thành", "xem_chi_tiet": "Xem chi tiết"},
        {"ten_sach": "Ulysses", "ngay_thao_tac": "22 April 2024", "thao_tac": "Sách nói", "tinh_trang": "Đã huỷ", "xem_chi_tiet": "Xem chi tiết"},
        {"ten_sach": "Les Misérables", "ngay_thao_tac": "20 April 2024", "thao_tac": "Lưu trữ", "tinh_trang": "Đang xử lý", "xem_chi_tiet": "Xem chi tiết"},
        {"ten_sach": "Anna Karenina", "ngay_thao_tac": "18 April 2024", "thao_tac": "Lưu sách", "tinh_trang": "Không thành công", "xem_chi_tiet": "Xem chi tiết"},
        {"ten_sach": "One Hundred Years of Solitude", "ngay_thao_tac": "15 April 2024", "thao_tac": "Cộng đồng", "tinh_trang": "Đang xử lý", "xem_chi_tiet": "Xem chi tiết"}
    ]
    return render_template('dashboard.html', data=data, books=books)

@main_bp.route('/signin')
def signin():
    return render_template('signin.html')

@main_bp.route('/signup')
def signup():
    return render_template('signup.html')

@main_bp.route('/detail')
def detail():
    return render_template('detail.html')

@main_bp.route('/book')
def book():
    return render_template('book.html')


@main_bp.route('/book/publish', methods=['GET'])
def book_publish():
    book_data = session.get('book_data')
    if not book_data:
        return redirect(url_for('main_bp.book'))
    return render_template('book-publish.html', book_data=book_data)


@main_bp.route('/book/detail', methods=['GET'])
def book_detail():
    book_data = session.get('book_data')
    if not book_data:
        return redirect(url_for('main_bp.book'))
    return render_template('book-detail.html', book_data=book_data)

@main_bp.route('/book/translate', methods=['GET'])
def book_translate():
    book_data = session.get('book_data')
    if not book_data:
        return redirect(url_for('main_bp.book'))
    return render_template('book-translate.html', book_data=book_data)

@main_bp.route('/book/speech', methods=['GET'])
def book_speech():
    book_data = session.get('book_data')
    if not book_data:
        return redirect(url_for('main_bp.book'))
    return render_template('book-speech.html', book_data=book_data)


@main_bp.route('/book/upload', methods=['GET'])
def book_upload():
    book_data = session.get('book_data')
    user_id = session.get('user')['uid'] if 'user' in session else None
    if not book_data:
        return redirect(url_for('main_bp.book'))
    if not user_id:
        flash('Please sign in to upload to cloud')
        return redirect(url_for('main_bp.signin'))  # Redirect to sign in if user is not logged in
    return render_template('book-upload.html', book_data=book_data, user_id=user_id)

@main_bp.route('/book/read', methods=['GET'])
def book_read():
    book_data = session.get('book_data')
    if not book_data:
        return redirect(url_for('main_bp.book'))
    return render_template('book-read.html', book_data=book_data)

@main_bp.route('/book/load/<book_id>', methods=['GET'])
def book_load(book_id):
    db = current_app.config['FIRESTORE']
    book_ref = db.collection('published_books').document(book_id)
    book_doc = book_ref.get()

    if book_doc.exists:
        book_data = book_doc.to_dict().get('book_data', {})
        # Transform the data structure to include metadata
        transformed_book_data = {
            'metadata': {
                'title': book_data.get('metadata', {}).get('title', 'Unknown Title'),
                'authors': book_data.get('metadata', {}).get('authors', ['Unknown Authors']),
                'subject': book_data.get('metadata', {}).get('subject', 'Unknown Subject'),
                'keywords': book_data.get('metadata', {}).get('keywords', 'Unknown Keywords'),
            },
            'cover_image': book_data.get('cover_image', 'None'),
            'texts': book_data.get('texts', {}),
            'storage_url': book_data.get('storage_url', ''),
            'user_id': book_data.get('user_id', 'Unknown User'),
            'created_date': book_data.get('created_date', 'Unknown Date'),
            'public': book_data.get('public', False)
        }
        session['book_data'] = transformed_book_data
        return redirect(url_for('main_bp.book_read'))
    else:
        return jsonify({'error': 'Book not found'}), 404



@main_bp.route('/user', methods=['GET'])
@main_bp.route('/user/<identifier>', methods=['GET'])
def user(identifier=None):
    db = current_app.config['FIRESTORE']

    # Get current user id from session if identifier is not provided
    if identifier is None:
        user_data = session.get('user')
        if not user_data:
            return redirect(url_for('main_bp.signin'))
        user_id = user_data['uid']
    else:
        # Determine if identifier is an email or user_id
        if '@' in identifier:
            # Fetch user by email
            users_ref = db.collection('users').where('email', '==', identifier)
            user_docs = users_ref.stream()
            user_doc = next(user_docs, None)  # Get the first matching document
            if not user_doc:
                return jsonify({'error': 'User not found'}), 404
            user_id = user_doc.id
            user_data = user_doc.to_dict()
        else:
            # Fetch user by user_id
            user_ref = db.collection('users').document(identifier)
            user_doc = user_ref.get()
            if not user_doc.exists:
                return jsonify({'error': 'User not found'}), 404
            user_id = identifier
            user_data = user_doc.to_dict()

    # Fetch user's published books
    published_books_ref = db.collection('published_books').where('user_id', '==', user_id)
    published_books_docs = published_books_ref.stream()
    published_books = []
    for doc in published_books_docs:
        book_data = doc.to_dict().get('book_data', {})
        book_data['id'] = doc.id
        if 'metadata' not in book_data:
            book_data['metadata'] = {}  # Ensure metadata exists
        published_books.append(book_data)
        
    # Fetch user's books
    books_ref = db.collection('books').where('user_id', '==', user_id)
    books_docs = books_ref.stream()
    books = []
    for doc in books_docs:
        book_data = doc.to_dict().get('book_data', {})
        book_data['id'] = doc.id  # Add the document ID
        if 'metadata' not in book_data:
            book_data['metadata'] = {}  # Ensure metadata exists
        books.append(book_data)

    # Fetch user's files from storage
    bucket = current_app.config['STORAGE']
    blobs = bucket.list_blobs(prefix=f"users/{user_id}/books/")
    user_files = [blob.name for blob in blobs]

    return render_template('user.html', user_data=user_data, published_books=published_books, books=books, user_files=user_files)

functions/app/templates/animation.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="Tran Minh Giang"/>
    <title>Animation</title>

    <link rel="stylesheet" href="styles/desktop.css">
    <link rel="stylesheet" href="styles/mobile.css">

    <script src="https://unpkg.com/@phosphor-icons/web"></script>
</head>


<body>
    <div class="bgr"></div>
    <div class="zid-01 s-30 bl-15 r-20 t-50 ln-1"></div>
    <div class="zid-01 s-40 bl-25 r-10 ln-1" style="top: 200vh;"></div>
    <div class="zid-01 s-50 bl-25 l-10 t-80 zid-01" style="background-color: rgb(198, 22, 22); position: fixed;"></div>

  <!-- navbar -->
    <header class="pst-fx w-100 zid-3" tabindex="1">
        <div class="h-10 mg-h-20vw jtf-btw alit-ct">
            <h1 class="clf">Realestzan</h1>
            <nav class="jtf-evl bs-6 ">
                <a class="fs-15" href="welcome.html">Welcome</a>
                <a class="fs-15" href="questions.html">Questions</a>
                <a class="fs-15" href="detail.html">Detail</a>
            </nav>
            <a class="fs-1" href="animation.html">👉🏻 Animation 👈🏻</a>
        </div>

        <div class="rlt w-100 h-10" style="margin-top: -10vh; backdrop-filter: blur(20px); z-index: -3;"></div>
    </header>

    <main>
            <div class="jtf-cl-st ct">
                <h3 class="fs-25 mg-t-20vh">My animation</h3>
                <strong class="fs-4 fw-3 pd-v-3">Used in this project</strong>
            </div>
          

            <div class="rd-5 mg-t-5r mg-h-20vw jtf-btw card pd-5r">
                <div class="bs-5">
                    <strong class="fs-25 fw-9">Image animation</strong>
                    <p class="fs-15 lh-3 fw-3 pd-t-3r">Rotate when Hover</p>
                    <p class="fs-15 lh-3 pd-t-3r">Used in all pages </p>
                </div>
                <img class="w-20 h-30 sc-14" src="/images/laptop.png" alt="">
            </div>
            
            <div class="rd-5 mg-t-5r mg-h-20vw card pd-5r">
                <strong class="fs-25 fw-9">Dropdown animation</strong>
                <p class="fs-15 lh-3 fw-3 pd-t-3r">Used in <a class="fw-5 pd-h-1" href="questions.html">Questions</a> page</p>
                <div class="mg-t-10vw jtf-btw mg-t-10vh">
                    <div class="job-item w-50 pd-h-3 pd-v-2" tabindex="0">
                        <h2 class="fs-3 fw-9">01</h2>
                        <div class="jtf-st h-10 alit-ct">
                            <i class="ph ph-plus-circle fs-3"></i>
                            <p class="fs-2 mg-l-2r">Press me</p>
                        </div>
                        <p class="fs-15 fw-3 lh-3">I'm a dropdown</p>
                    </div>
                
                    <div class="job-item w-50 pd-h-3 pd-v-2" tabindex="0">
                        <h2 class="fs-3 fw-9">02</h2>
                        <div class="jtf-st h-10 alit-ct">
                            <i class="ph ph-plus-circle fs-3"></i>
                            <p class="fs-2 mg-l-2r">Press me</p>
                        </div>
                        <p class="fs-15 fw-3 lh-3">I'm also a dropdown</p>
                    </div>
                </div>
            </div>

            <div class="rd-5 mg-t-5r mg-h-20vw card pd-5r">
                <strong class="fs-25 fw-9">Navigation animation</strong>
                <p class="fs-15 lh-3 fw-3 pd-t-2r">When in mobile responsive</p>
            </div>


    </main>

    <!-- footer -->
    <footer class="w-100 h-40 mg-20vw jtf-evl alit-ct mg-t-20vh">
        <div class="h-80pc jtf-cl-btw">
            <strong>Navigation</strong>
            <a href="welcome.html" class="fs-2r">👉🏻 Welcome 👈🏻</a>
            <a href="questions.html" class="fs-2r">Questions</a>
            <a href="detail.html" class="fs-2r">Detail</a>
        </div>
  
        <div class="h-80pc jtf-cl-btw">
            <strong>Contact</strong>
            <a>0949010705</a>
            <a href="welcome.html">realestzan.com</a>
            <a>franbow1177@</a>
        </div>
  
          <div class="h-80pc jtf-cl-btw">
              <strong>Contact</strong>
              <div class="alit-ct"><i class="fs-2 mg-r-2r ph ph-meta-logo"></i><p>/010705mariposa</p></div>
              <div class="alit-ct"><i class="fs-2 mg-r-2r ph ph-twitter-logo"></i><p>/none</p></div>
              <div class="alit-ct"><i class="fs-2 mg-r-2r ph ph-linkedin-logo"></i><p>/none</p></div>
          </div>
    </footer>
</body>
</html>

functions/app/templates/book-speech.html
{% extends "base.html" %}

{% block title %}User Info{% endblock %}

{% block breadcrumbs %}
<a href="{{ url_for('main_bp.book') }}" class="hover:text-background-light">Books</a>
<span class="mx-2 text-gray-600">/</span>
<a href="{{ url_for('main_bp.book_upload') }}" class="hover:text-background-light">Speech<a>
{% endblock %}

{% block content %}
<main class="rounded-lg">
    
    <h1 class="text-3xl font-bold mb-4 flex gap-4 items-center"><img width="50" height="50" src="{{ url_for('static', filename='images/speech.png') }}" alt=""><span class="text-2xl font-semibold">Sách nói: {{ book_data.metadata.title }}</h1>
    <form id="speechForm" class="mb-4">
        <input type="hidden" name="book_data" value="{{ book_data.texts }}">
        <button type="button" onclick="submitSpeechForm()" class="bg-background-dark hover:bg-secondary text-background-light hover:text-background-dark font-bold py-2 px-4 rounded mt-4 inline-block">Generate Speech</button>
    </form>
    <div id="progressContainer" style="display: none;" class="mb-4">
        <h2 class="text-xl font-bold mb-2">Speech Generation Progress</h2>
        <progress id="progressBar" value="0" max="100" class="w-full h-4 bg-gray-200 rounded-lg"></progress>
    </div>
    <div id="audioContainer" style="display: none;" class="mb-4">
        <h2 class="text-xl font-bold mb-2">Generated Audio</h2>
        <audio id="audioPlayer" controls class="w-full">
            <source id="audioSource" src="" type="audio/wav">
            Your browser does not support the audio element.
        </audio>
        <a id="downloadButton" href="#" download="output.wav" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mt-4 inline-block">Tải File Audio</a>
        <a id="downloadButton" href="#" download="output.wav" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mt-4 inline-block">Lưu trữ Đám mây</a>
    </div>

    <div class="mt-6">
        {% for page, text in book_data.texts.items() %}
            <div class="mb-6">
                <h2 class="text-xl font-semibold">{{ page }}</h2>
                <p class="text-lg">{{ text }}</p>
            </div>
        {% endfor %}
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.0.1/socket.io.js"></script>
    <script>
        document.addEventListener('DOMContentLoaded', (event) => {
            const socket = io();

            socket.on('progress', (data) => {
                const progressBar = document.getElementById('progressBar');
                progressBar.value = data.progress;
            });

            window.submitSpeechForm = function() {
                const form = document.getElementById('speechForm');
                const formData = new FormData(form);
                const book_data = {{ book_data.texts | tojson }};
                const socket_id = socket.id;

                document.getElementById('progressContainer').style.display = 'block';

                fetch('/api/book/speech', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json'
                    },
                    body: JSON.stringify({ text: Object.values(book_data).join('\n'), socket_id })
                })
                .then(response => response.blob())
                .then(blob => {
                    const url = window.URL.createObjectURL(blob);
                    const audioPlayer = document.getElementById('audioPlayer');
                    const audioSource = document.getElementById('audioSource');
                    const downloadButton = document.getElementById('downloadButton');

                    audioSource.src = url;
                    audioPlayer.load();
                    downloadButton.href = url;
                    downloadButton.style.display = 'inline-block';

                    document.getElementById('progressContainer').style.display = 'none';
                    document.getElementById('audioContainer').style.display = 'block';
                })
                .catch(error => {
                    console.error('Error:', error);
                    document.getElementById('progressContainer').style.display = 'none';
                });
            };
        });
    </script>
</main>
{% endblock %}

functions/app/templates/book-upload.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Upload Book (to Firebase Storage)</title>
</head>
<body>
    <h1>Upload Book: {{ book_data.metadata.title }}</h1>
    <form action="/storage/upload/{{ user_id }}" method="post" enctype="multipart/form-data">
        <label for="file">Choose file to upload:</label><br>
        <input type="file" id="file" name="file" required><br><br>
        <button type="submit">Upload to Firebase Storage</button>
    </form>
</body>
</html>

functions/app/templates/book.html
{% extends "base.html" %}

{% block title %}Upload{% endblock %}

{% block breadcrumbs %}
<a href="{{ url_for('main_bp.book') }}" class="dark:text-white">Books</a>
<span class="mx-2 text-gray-600">/</span>
<a href="{{ url_for('main_bp.book_upload') }}" class="dark:text-white">Upload<a>
{% endblock %}

{% block content %}
<main class="p-4 w-full min-h-[80vh] flex items-center">

    <section class="bg-background-dark/5 w-fit rounded-lg mx-auto my-auto dark:bg-gray-900">
        <form id="upload-form" class="p-24 mx-auto max-w-screen-xl text-center lg:py-16 lg:px-12">
            <a href="#" class="inline-flex justify-between items-center py-1 px-1 pr-4 mb-7 text-sm text-gray-700 bg-gray-100 rounded-full dark:bg-gray-800 dark:text-white hover:bg-gray-200 dark:hover:bg-gray-700" role="alert">
                <span class="text-xs bg-primary rounded-full text-white px-4 py-1.5 mr-3">Trợ giúp</span> <span class="text-sm font-medium">Nếu có vấn đề, báo cáo ở đây</span> 
                <svg class="ml-2 w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd"></path></svg>
            </a>
            <h1 class="mb-4 text-4xl font-extrabold tracking-tight leading-none text-gray-900 md:text-5xl lg:text-6xl dark:text-white">Bắt đầu đăng tải file Sách ngay</h1>
            <p class="mb-8 text-lg font-normal text-gray-500 lg:text-xl sm:px-16 xl:px-48 dark:text-gray-400">Chúng tôi hỗ trợ các định dạng .txt, .mobi. .pdf và .epub.</p>

<input type="file" id="file" name="file" accept=".pdf,.txt,.epub,.mobi" required  class="mx-auto block mb-8 w-[14vw] text-sm text-gray-900 border border-gray-300 rounded-lg cursor-pointer bg-gray-50 dark:text-gray-400 focus:outline-none dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400" id="file_input" type="file">

            <div class="flex flex-col mb-8 lg:mb-16 space-y-4 sm:flex-row sm:justify-center sm:space-y-0 sm:space-x-4">
                <Button type="button" onclick={submitUploadForm()} >
                    <a class="inline-flex justify-center items-center py-3 px-5 text-base font-medium text-center text-white rounded-lg bg-primary hover:bg-primary-800 focus:ring-4 focus:ring-primary-300 dark:focus:ring-primary-900">
                        Đăng sách
                        <svg class="ml-2 -mr-1 w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
                    </a>
                </Button>
                <a class="inline-flex justify-center items-center py-3 px-5 text-base font-medium text-center text-gray-900 rounded-lg border border-gray-300 hover:bg-gray-100 focus:ring-4 focus:ring-gray-100 dark:text-white dark:border-gray-700 dark:hover:bg-gray-700 dark:focus:ring-gray-800">
                    <!-- <svg class="mr-2 -ml-1 w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M2 6a2 2 0 012-2h6a2 2 0 012 2v8a2 2 0 01-2 2H4a2 2 0 01-2-2V6zM14.553 7.106A1 1 0 0014 8v4a1 1 0 00.553.894l2 1A1 1 0 0018 13V7a1 1 0 00-1.447-.894l-2 1z"></path></svg> -->
                    Gửi trực tiếp
                </a>  
                {% include 'signin-button.html' %}
            </div>
            <div id="progress-container" class="mt-8 hidden">
                <p class="text-lg font-medium text-gray-700">Cập nhật:</p>
                <div class="w-full bg-gray-200 rounded-full h-4 mt-2">
                    <div id="progress-bar" class="bg-primary h-4 rounded-full text-center text-xs font-medium text-white leading-none" style="width: 0%"></div>
                </div>
            </div>
            <div class="px-4 mx-auto text-center md:max-w-screen-md lg:max-w-screen-lg lg:px-36">
                <span class="font-semibold text-gray-400 uppercase">TÍNH NĂNG</span>
                <div class="flex flex-wrap justify-center items-center mt-8 text-gray-500 sm:justify-between">
                    <div class="flex items-center text-3xl font-bold">
                        <img src="../static/images/translate.png" class="h-36  p-8" />
                        <p>Dịch sách</p>
                    </div>
                    <div class="flex items-center text-3xl font-bold">
                        <img src="../static/images/speech.png" class="h-36  p-8" />
                        <p>Sách nói</p>
                    </div>
                    <div class="flex items-center text-3xl font-bold">
                        <img src="../static/images/storage.png" class="h-36 p-8" />
                        <p>Lưu trữ</p>
                    </div>
                </div>
            </div> 

        </>
    </section>



</main>

<script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.0.1/socket.io.js"></script>

<script>
    const socket = io();

    socket.on('progress', (data) => {
        const progressBar = document.getElementById('progress-bar');
        progressBar.style.width = `${data.progress}%`;
        // progressBar.textContent = `${data.progress}%`;
    });

    function submitUploadForm() {   
    const form = document.getElementById('upload-form');
    const fileInput = document.getElementById('file');

    if (!fileInput.files.length) {
        Swal.fire({
            title: 'Error!',
            text: 'Select a file to upload',
            icon: 'error',
            confirmButtonText: 'Cool'
        });
        return;
    }

    const file = fileInput.files[0];
    const formData = new FormData();
    formData.append('file', file);

    document.getElementById('progress-container').classList.remove('hidden');
    const socket_id = socket.id;

    fetch('/book/extract', {
        method: 'POST',
        headers: {
            'Accept': 'application/json'
        },
        body: formData
    })
    .then(response => response.text()) // Read response as text
    .then(responseText => {
        try {
            const data = JSON.parse(responseText); // Attempt to parse JSON
            if (data.error) {
                Swal.fire({
                    title: 'Error!',
                    text: 'Failed to upload the book: ' + data.error,
                    icon: 'error',
                    confirmButtonText: 'Cool'
                });
            } else {
                // Optionally, redirect to another page or update the UI
                window.location.href = "{{ url_for('main_bp.book_detail') }}";
            }
        } catch (error) {
            console.error('Error parsing JSON:', error, responseText);
            Swal.fire({
                title: 'Error!',
                text: 'Failed to upload the book.',
                icon: 'error',
                confirmButtonText: 'Cool'
            });
        }
        document.getElementById('progress-container').classList.add('hidden');
    })
    .catch(error => {
        console.error('Error:', error);
        Swal.fire({
            title: 'Error!',
            text: 'Failed to upload the book.',
            icon: 'error',
            confirmButtonText: 'Cool'
        });
        document.getElementById('progress-container').classList.add('hidden');
    });

    // Emit a Socket.IO event with the session ID
    socket.emit('start_upload', { socketio_id: socket_id });
}

</script>
{% endblock %}